name: anselm-kuesters-backend
services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - /home/destroflyer/anselm-kuesters/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 0
    restart: always
  db-ui:
    image: destrostudios/phpmyadmin
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "1338:443"
    restart: always
  app:
    build:
      dockerfile: app.Dockerfile
      args:
        DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    depends_on:
      db:
        condition: service_healthy
    restart: always
  app-proxy:
    build:
      dockerfile: proxy.Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "1337:443"
    restart: always
  api-custom:
    build:
      dockerfile: api-custom.Dockerfile
    environment:
      DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - "127.0.0.1:1339:80"
    restart: always
